MLOG_DAMAGE 		= 0
MLOG_OTHER 			= 1
MLOG_SHOTS 			= 2
MLOG_PLAYER 		= 3
MLOG_PLAYERS 		= 4
MLOG_WITNESS 		= 5


MLOGS_WITNESS 		= 0
MLOGS_SWITCH_TO 	= 1
MLOGS_SWITCH_FROM	= 2
MLOGS_FIRE			= 3

/*
local e = {}
e.EVENT_PLY_WITNESS 	= 0
e.EVENT_PLY_SWITCH 		= 1
e.EVENT_PLY_SHOT 		= 2

e.EVENT_AUTOSLAY 		= 3
e.EVENT_BODY_FOUND 		= 4
e.EVENT_CREDITS_FOUND 	= 5

e.EVENT_C4_PLANT		= 6
e.EVENT_C4_ARM 			= 7
e.EVENT_C4_DISARM 		= 8
e.EVENT_C4_DESTROY 		= 9
e.EVENT_C4_PICKUP 		= 10
e.EVENT_C4_EXPLODE 		= 11

e.EVENT_CREDITS_GIVE	= 12
e.EVENT_CREDITS_GET		= 13

e.EVENT_DNA_FOUND		= 14
e.EVENT_DNA_SCAN		= 15
e.EVENT_DNA_REQ			= 16

e.EVENT_PLY_HURT		= 17
e.EVENT_PLY_DROWN		= 18
e.EVENT_PLY_FALL		= 19
e.EVENT_PLY_PUSH		= 20

e.EVENT_PLY_HEAL		= 21
e.EVENT_PLY_KILL		= 22

e.EVENT_PLY_TBUTTON		= 23
e.EVENT_PLY_TELEPORT	= 24
e.EVENT_PLY_USE			= 25

e.EVENT_PLY_NADE_USE	= 26
e.EVENT_PLY_NADE_THROW	= 27
e.EVENT_PLY_NADE_IMPACT	= 28

e.EVENT_PLY_SUICIDE		= 29

e.EVENT_PLY_RADIO		= 30
e.EVENT_PLY_KOS			= 31
e.EVENT_PLY_CHAT		= 32
e.EVENT_PLY_VOICE		= 33

e.EVENT_PLY_ORDER		= 34
e.EVENT_WACKY			= 35
e.EVENT_SEE_UNID		= 36
e.EVENT_WALK_UNID		= 37

e.EVENT_PLY_MAGNETO		= 38
e.EVENT_PLY_HANG		= 39
e.EVENT_PLY_THROW		= 40


mlogs.eventids = e*/