ITEM.ID = 3394
ITEM.Name = "Cinco De Mayo"
ITEM.Description = "This box contains an item from the Cinco De Mayo Collection! Right click to open"
ITEM.Image = "https://static.moat.gg/ttt/icon_crate_cincodemayo.png"
ITEM.Rarity = 3
ITEM.NameEffect = "enchanted"
ITEM.NameColor = Color(255, 45, 45)
ITEM.NameEffectMods = {Color(45, 255, 45)}
ITEM.Collection = "Cinco de Mayo Collection"
ITEM.Active = true
ITEM.Stackable = true
ITEM.Price = 5550
-- ITEM.ChosenRarity = 8
ITEM.LimitedShop = 1589958000
ITEM.Rewardable = true
ITEM.NotDroppable = true