ITEM.ID = 7332
ITEM.Name = "Paper Tiqers Crate"
ITEM.Description = "This crate contains a skin from the Paper Tiqers Collection! Right click to open"
ITEM.Image = "https://static.moat.gg/ttt/uwu/pluto/icon_crate.png"
ITEM.Rarity = 4
ITEM.Collection = "Paper Tiqers Collection"
ITEM.Active = true
ITEM.Stackable = true
ITEM.Price = 2000
ITEM.NewItem = 1577779200