ITEM.ID = 851
ITEM.Name = "Easter Egg"
ITEM.Description = "This egg contains a rare item from the Egg Hunt Collection! Right click to open"
ITEM.Image = "https://cdn.moat.gg/f/easter_egg64.png" 
ITEM.Rarity = 8
ITEM.Collection = "Egg Hunt Collection"
ITEM.Active = false
ITEM.Stackable = true
ITEM.Price = 350