ITEM.ID = 8997
ITEM.Name = "Golden Easter Basket"
ITEM.Description = "This basket contains a rare item from the Easter Collection! Right click to open"
ITEM.Image = "https://static.moat.gg/f/easter_basket64.png"
ITEM.Rarity = 8
ITEM.Collection = "Golden Easter Collection"
ITEM.Contains = {"Easter Collection"}
ITEM.Active = false
ITEM.Stackable = true
ITEM.NotDroppable = true
ITEM.IgnoreDiscord = true
ITEM.Price = 350
ITEM.WeaponForcePercent = 0
ITEM.ChosenRarity = 3
local rarity = 1 / 3
ITEM.Rarities = {
    [5] = rarity,
    [6] = rarity,
    [7] = rarity
}