ITEM.ID = 8999
ITEM.Name = "Easter Basket"
ITEM.Description = "This basket contains a rare item from the Easter Collection! Right click to open"
ITEM.Image = "https://static.moat.gg/f/easter_basket64.png"
ITEM.Rarity = 8
ITEM.Collection = "Easter Collection"
ITEM.Active = false
ITEM.Stackable = true
ITEM.Price = 350
ITEM.ChosenRarity = 8
ITEM.IgnoreDiscord = true
ITEM.NotDroppable = true