ITEM.ID = 8998
ITEM.Name = "Easter 2019 Basket"
ITEM.Description = "This basket contains a rare item from the Easter Collection! Right click to open"
ITEM.Image = "https://cdn.moat.gg/f/easter_basket64.png"
ITEM.Rarity = 8
ITEM.Collection = "Easter Collection"
ITEM.Contains = {"Egg Hunt Collection", "Easter Collection"}
ITEM.Active = false
ITEM.Stackable = true
ITEM.Price = 350
ITEM.WeaponForcePercent = 0
ITEM.ChosenRarity = 8
ITEM.Rarities = {
    [3] = 0.24,
    [4] = 0.12,
    [5] = 0.05,
    [6] = 0.0125,
    [7] = 0.0017,
    [9] = 0.0001,
}
ITEM.IgnoreDiscord = true
ITEM.NotDroppable = true