ITEM.ID = 8999
ITEM.Name = "Easter Basket"
ITEM.Description = "This basket contains an item from the Easter 2018 Collection! Right click to open"
ITEM.Image = "https://cdn.moat.gg/f/HPl3JXt851WFKcCLEoRABm1SnNOJ.png"
ITEM.Rarity = 8
ITEM.Collection = "Easter 2018 Collection"
ITEM.Active = false
ITEM.Stackable = true
ITEM.Price = 350
ITEM.ChosenRarity = 8