ITEM.ID = 8151
ITEM.Name = "Hype Crate"
ITEM.Description = "This crate contains an item from the Hype Collection! Right click to open"
ITEM.Image = "https://cdn.moat.gg/f/3043b.png"
ITEM.Rarity = 3
ITEM.Collection = "Hype Collection"
ITEM.Active = false
ITEM.Stackable = true
ITEM.Price = 500
ITEM.NewItem = 1541818391