ITEM.ID = 6000
ITEM.Name = "Paint Crate"
ITEM.Description = "This crate contains an item from the Paint Collection! Right click to open"
ITEM.Image = "https://static.moat.gg/ttt/paint_crate.png"
ITEM.Rarity = 3
ITEM.Collection = "Paint Collection"
ITEM.Active = true
ITEM.Stackable = true
ITEM.Price = 1400