ITEM.ID = 2001
ITEM.Name = "Pumpkin Crate"
ITEM.Description = "This crate contains an item from the Pumpkin Collection! Right click to open"
ITEM.Image = "https://cdn.moat.gg/f/ThixfHLFUCYkO2FMo6IQ5fIzz3jT.png" 
ITEM.Rarity = 8
ITEM.Collection = "Pumpkin Collection"
ITEM.Active = false
ITEM.Stackable = true
ITEM.Price = 50000