ITEM.ID = 2003
ITEM.Name = "Skin Crate"
ITEM.Description = "This crate contains an item from the Skin Collection! Right click to open"
ITEM.Image = "https://cdn.moat.gg/f/nJJCpROg6XLl3AJhXthmMa9YD1XV.png" 
ITEM.Rarity = 4
ITEM.Collection = "Skin Collection"
ITEM.Active = true
ITEM.Stackable = true
ITEM.Price = 1200
ITEM.NewItem = 1548892800