ITEM.ID = 1051
ITEM.Name = "Titan Crate"
ITEM.Description = "This crate contains an item from the Titan Collection! Right click to open"
ITEM.Image = "https://cdn.moat.gg/f/VRfIdxR5Or4GYC3ULukcdwdx0SvT.png"
ITEM.Rarity = 4
ITEM.Collection = "Titan Collection"
ITEM.Active = true
ITEM.Stackable = true
ITEM.Price = 2000