mlogs.cfg:AddGroup("communitylead", true, true)
mlogs.cfg:AddGroup("headadmin", true, true)
mlogs.cfg:AddGroup("senioradmin", false, true)
mlogs.cfg:AddGroup("admin", false, true)
mlogs.cfg:AddGroup("moderator", false, true)
mlogs.cfg:AddGroup("trialstaff", false, true)