ttt = ttt or {}
ttt.MinimumPlayers = 2

-- Colors
COLOR_WHITE = Color(255, 255, 255, 255)
COLOR_BLACK = Color(0, 0, 0, 255)
COLOR_GREEN = Color(0, 255, 0, 255)
COLOR_DGREEN = Color(0, 100, 0, 255)
COLOR_RED = Color(255, 0, 0, 255)
COLOR_YELLOW = Color(200, 200, 0, 255)
COLOR_LGRAY = Color(200, 200, 200, 255)
COLOR_BLUE = Color(0, 0, 255, 255)
COLOR_NAVY = Color(0, 0, 100, 255)
COLOR_PINK = Color(255, 0, 255, 255)
COLOR_ORANGE = Color(250, 100, 0, 255)
COLOR_OLIVE = Color(100, 100, 0, 255)
-- Round status
ROUND_WAIT = 1
ROUND_PREP = 2
ROUND_ACTIVE = 3
ROUND_POST = 4
-- Game event log defs
EVENT_KILL = 1
EVENT_SPAWN = 2
EVENT_GAME = 3
EVENT_FINISH = 4
EVENT_SELECTED = 5
EVENT_BODYFOUND = 6
EVENT_C4PLANT = 7
EVENT_C4EXPLODE = 8
EVENT_CREDITFOUND = 9
EVENT_C4DISARM = 10
WIN_NONE = 1
WIN_TRAITOR = 2
WIN_INNOCENT = 3
WIN_JESTER = 4
WIN_KILLER = 5
WIN_TIMELIMIT = 6
-- Weapon categories, you can only carry one of each
WEAPON_NONE = 0
WEAPON_MELEE = 1
WEAPON_PISTOL = 2
WEAPON_HEAVY = 3
WEAPON_NADE = 4
WEAPON_CARRY = 5
WEAPON_EQUIP1 = 6
WEAPON_EQUIP2 = 7
WEAPON_ROLE = 8
WEAPON_EQUIP = WEAPON_EQUIP1
WEAPON_UNARMED = -1
-- Kill types discerned by last words
KILL_NORMAL = 0
KILL_SUICIDE = 1
KILL_FALL = 2
KILL_BURN = 3
-- Entity types a crowbar might open
OPEN_NO = 0
OPEN_DOOR = 1
OPEN_ROT = 2
OPEN_BUT = 3
OPEN_NOTOGGLE = 4 --movelinear
-- Mute types
MUTE_NONE = 0
MUTE_TERROR = 1
MUTE_ALL = 2
MUTE_SPEC = 1002
-- Player roles
ROLE_INNOCENT = 0
ROLE_TRAITOR = 1
ROLE_DETECTIVE = 2
-- Custom Edit
ROLE_JESTER = 3
ROLE_KILLER = 4
ROLE_DOCTOR = 5
ROLE_BEACON = 6
ROLE_SURVIVOR = 7
ROLE_HITMAN = 8
ROLE_BODYGUARD = 9
ROLE_VETERAN = 10
ROLE_XENOMORPH = 11
ROLE_WITCHDOCTOR = 12
ROLE_MAX = ROLE_WITCHDOCTOR
ROLE_NONE = ROLE_INNOCENT

local basic_roles = {
    [ROLE_INNOCENT] = {
        ROLE_INNOCENT, ROLE_DOCTOR, ROLE_DETECTIVE, ROLE_BEACON, ROLE_SURVIVOR, ROLE_BODYGUARD, ROLE_VETERAN, ROLE_XENOMORPH, ROLE_WITCHDOCTOR
    },
    [ROLE_TRAITOR] = {
        ROLE_TRAITOR, ROLE_HITMAN
    },
    [ROLE_JESTER] = {
        ROLE_JESTER
    },
    [ROLE_KILLER] = {
        ROLE_KILLER
    }
}

BASIC_ROLE_LOOKUP = {}
for basic, roles in pairs(basic_roles) do
    for i, role in ipairs(roles) do
        BASIC_ROLE_LOOKUP[role] = basic
    end
end