local Add = mi.Weapons.Register
------------------------------------
--
-- 	Inventory ClassName Enumerations
--
------------------------------------

Add(1, 'weapon_ttt_te_sr25', 'SR-25')
Add(2, 'weapon_ttt_cse', 'Visualizer')
Add(3, 'weapon_ttt_bouncy_monkas', 'Bouncy monkaS')
Add(4, 'weapon_ttt_jihad', 'Jihad Bomb')
Add(5, 'weapon_acidball', 'Contagio')
Add(6, 'ai_weapon_bow_falmer', nil)
Add(7, 'weapon_ttt_finger', 'DNA Eradicator')
Add(8, 'weapon_ttt_rsb', 'Remote Sticky Bomb')
Add(9, 'weapon_ttt_mp5', 'MP5')
Add(10, 'weapon_pvpsword', 'Sword')
Add(11, 'weapon_ttt_te_fal', 'FAL')
Add(12, 'weapon_ttt_bouncy_feelsbadman', 'Bouncy FeelsBadMan')
Add(13, 'weapon_ttt_bouncy_heartpepe', 'Bouncy HeartPepe')
Add(14, 'weapon_ttt_te_m24', 'M24')
Add(15, 'ai_weapon_base_sword', nil)
Add(16, 'weapon_patriot', 'The Patriot')
Add(17, 'weapon_ttt_confgrenade', 'Discombobulator')
Add(18, 'weapon_zm_shotgun', 'XM1014')
Add(19, 'weapon_ttt_bouncy_trihard', 'Bouncy TriHard')
Add(20, 'weapon_ttt_push', 'Newton Launcher')
Add(21, 'weapon_ttt_taunt_salute', 'Salute Taunt')
Add(22, 'weapon_ttt_stungun', 'UMP Prototype')
Add(23, 'weapon_ttt_te_m14', 'M14A1')
Add(24, 'weapon_ttt_taunt_test2', 'Sexy Taunt')
Add(25, 'weapon_frostball', 'Glacies')
Add(26, 'weapon_ttt_keyboard', 'A Keyboard')
Add(27, 'weapon_ttt_disarmer', 'Disarmer')
Add(28, 'weapon_ttt_ocpistol', 'One Shot Revolver')
Add(29, 'weapon_ttt_te_sterling', 'Sterling')
Add(30, 'weapon_zm_mac10', 'MAC10')
Add(31, 'weapon_fish', 'Fish')
Add(32, 'weapon_mor_daedric', 'Daedric Bow')
Add(33, 'weapon_ttt_flashbang', 'Flashbang')
Add(34, 'weapon_ttt_te_glock', 'Glock TE')
Add(35, 'weapon_virussil', 'Duel Silencers')
Add(36, 'weapon_ttt_tester', 'Portable Tester')
Add(37, 'weapon_ttt_taunt_lay', 'Lay Taunt')
Add(38, 'weapon_vape_mega', 'Mega Vape')
Add(39, 'ai_weapon_sword_draugr', nil)
Add(40, 'weapon_ttt_homebat', 'Homerun Bat')
Add(41, 'weapon_ttt_revolver', 'S&W 500')
Add(42, 'weapon_ttt_crossbow', 'Silenced Crossbow')
Add(43, 'weapon_minigun', 'Minigun')
Add(44, 'weapon_ttt_taunt_dab', 'Dab Taunt')
Add(45, 'ai_weapon_axe_battle_ebony', nil)
Add(46, 'weapon_tttbasegrenade', 'Incendiary grenade')
Add(47, 'weapon_ttt_te_mp5', 'MP5 FE')
Add(48, 'weapon_virustnt', 'TNT')
Add(49, 'weapon_ttt_manhack', 'Throwable Manhacks')
Add(50, 'weapon_ttt_te_1911', 'M1911')
Add(51, 'weapon_ttt_ak47', 'AK47')
Add(52, 'snowball_harmful', 'Snowball')
Add(53, 'weapon_possessor', 'Possessor')
Add(54, 'weapon_ttt_briefcase', 'Briefcase')
Add(55, 'weapon_predator_blade', 'Predator Blade')
Add(56, 'weapon_ttt_rollingpin', 'A Pot')
Add(57, 'weapon_ttt_mr96', 'Revolver')
Add(58, 'weapon_drachenbomb', 'Drachenlord')
Add(59, 'weapon_ttt_mac11', 'MAC11')
Add(60, 'weapon_biohazardball', 'Biohazard Ball')
Add(61, 'weapon_doubleb', 'Double Barrel')
Add(62, 'weapon_ttt_homingpigeon', 'Homing Pigeon')
Add(63, 'ai_translator', nil)
Add(64, 'weapon_ttt_m4a1', 'M4A1')
Add(65, 'weapon_ttt_bodyspawn', 'Death Faker')
Add(66, 'weapon_ttt_bouncy_hyperpoggers', 'Bouncy HyperPoggers')
Add(67, 'weapon_ttt_bouncy_poggers', 'Bouncy Poggers')
Add(68, 'weapon_sp', 'Stealth Pistol')
Add(69, 'weapon_ttt_sg550', 'SG550')
Add(70, 'weapon_ttt_m16', 'M16')
Add(71, 'snowball_harmless', 'Snowball')
Add(72, 'ttt_m9k_harpoon', 'Harpoon')
Add(73, 'weapon_ttt_baton', 'A Baton')
Add(74, 'boomer_gun_base', nil)
Add(75, 'weapon_ttt_fryingpan', 'Frying Pan')
Add(76, 'weapon_ttt_unarmed', 'Holstered')
Add(77, 'weapon_vape_custom', 'Custom Vape')
Add(78, 'weapon_vape_dragon', 'Dragon\'s Breath Vape')
Add(79, 'weapon_ttt_bouncy_peepohappy', 'Bouncy peepoHappy')
Add(80, 'nc_ttt_vss', nil)
Add(81, 'weapon_golden_revolver', 'Raging Bull 358')
Add(82, 'weapon_ttt_shotgun', 'Shotgun')
Add(83, 'weapon_ttt_te_g36c', 'G36C')
Add(84, 'weapon_xm8b', 'M8A1')
Add(85, 'weapon_ttt_wtester', 'DNA Scanner')
Add(86, 'weapon_zm_rifle', 'Rifle')
Add(87, 'weapon_ttt_ignite_station', 'Ignite Station')
Add(88, 'ai_weapon_base_axe_war', nil)
Add(89, 'weapon_zapperpvp', 'NES Zapper')
Add(90, 'weapon_xmasflash', 'Christmas Flash')
Add(91, 'weapon_ttt_te_m4a1', 'M4A1')
Add(92, 'weapon_ttt_fists', 'Fists')
Add(93, 'ai_weapon_bow_glass', nil)
Add(94, 'weapon_ttt_te_benelli', 'Benelli TE')
Add(95, 'weapon_zm_improvised', 'Crowbar')
Add(96, 'ai_weapon_base', nil)
Add(97, 'weapon_ttt_te_m9s', 'Beretta M9S')
Add(98, 'weapon_ttt_bouncy_pagchomp', 'Bouncy PagChomp')
Add(99, 'weapon_flechettegun', nil)
Add(100, 'ai_weapon_axe_war_ebony', nil)
Add(101, 'weapon_ttt_te_sg550', 'SG550 TE')
Add(102, 'weapon_ttt_jetpack', 'Jet Pack')
Add(103, 'weapon_ttt_bouncy_feelsspecialman', 'Bouncy FeelsSpecialMan')
Add(104, 'weapon_ttt_proximitymine', 'Proximity Mine')
Add(105, 'weapon_ttt_id_bomb_defuser', 'Identification Bomb Defuser')
Add(106, 'weapon_ttt_taunt_cheer', 'Cheer Taunt')
Add(107, 'weapon_ttt_taunt_wave', 'Wave Taunt')
Add(108, 'weapon_ttt_te_mac', 'MAC10 FE')
Add(109, 'weapon_ttt_radio', 'Radio')
Add(110, 'weapon_flakgun', 'Flak-28')
Add(111, 'weapon_ttt_smokegrenade', 'Smoke Grenade')
Add(112, 'weapon_vape_medicinal', 'Medicinal Vape')
Add(113, 'weapon_semiauto', 'Glock-17')
Add(114, 'weapon_ttt_te_cf05', 'CF05')
Add(115, 'weapon_zm_molotov', 'Molotov')
Add(116, 'weapon_ttt_taunt_dance', 'Dance Taunt')
Add(117, 'weapon_ttt_glock', 'Glock')
Add(118, 'weapon_mine_turtle', 'Mine Turtle')
Add(119, 'stalker_lr_300', 'LR-300')
Add(120, 'weapon_ttt_te_deagle', 'Deagle TE')
Add(121, 'weapon_ttt_taunt_sexy', 'Sexy Taunt')
Add(122, 'realistic_hook', 'Grappling Hook')
Add(123, 'weapon_ttt_sg552', 'SG552')
Add(124, 'weapon_ttt_meatcleaver', 'Meat Cleaver')
Add(125, 'weapon_ttt_chickennade', 'Chicken Egg')
Add(126, 'weapon_ttt_taunt_beacon', 'Call For Taunt')
Add(127, 'weapon_ttt_cz75', 'CZ-75')
Add(128, 'weapon_ttt_an94', 'Peacekeeper')
Add(129, 'weapon_ttt_bouncy_dontbully', 'Bouncy DontBully')
Add(130, 'weapon_ttt_galil', 'Galil')
Add(131, 'weapon_ttt_knife', 'Knife')
Add(132, 'ai_weapon_base_sword_great', nil)
Add(133, 'weapon_ttt_cloak', 'Cloaking Device')
Add(134, 'weapon_ttt_taunt_flail', 'Flail Taunt')
Add(135, 'weapon_ttt_binoculars', 'Binoculars')
Add(136, 'weapon_ttt_rev_confgrenade', 'Combobulator')
Add(137, 'weapon_ttt_bouncy_box', 'Bouncy Box')
Add(138, 'weapon_ttt_te_m9', 'Beretta M9')
Add(139, 'ai_weapon_sword_great_draugr', nil)
Add(140, 'weapon_fists', 'Fists')
Add(141, 'weapon_light_saber', 'Light Saber')
Add(142, 'weapon_vape_butterfly', 'Butterfly Vape')
Add(143, 'weapon_ttt_shorthealthgrenade', 'Health Grenade')
Add(144, 'weapon_mor_auriel', 'Auriel Bow')
Add(145, 'weapon_sandwich', 'Sandwich')
Add(146, 'weapon_katana', 'Katana')
Add(147, 'weapon_ttt_bouncy_meme', nil)
Add(148, 'weapon_ttt_bouncy_klappa', 'Bouncy Klappa')
Add(149, 'weapon_tomahawk', 'Tomahawk')
Add(150, 'weapon_ttt_bouncy_thankong', 'Bouncy Thankong')
Add(151, 'weapon_ttt_te_ak47', 'AK47 TE')
Add(152, 'weapon_ttt_bouncy_pepothink', 'Bouncy PepoThink')
Add(153, 'weapon_ttt_bouncy_pog', 'Bouncy Pog')
Add(154, 'ai_weapon_bow_draugr', nil)
Add(155, 'weapon_ttt_pull', 'Newton Puller')
Add(156, 'weapon_ttt_taunt_disagree', 'Disagree Taunt')
Add(157, 'ai_weapon_axe_war_draugr', nil)
Add(158, 'weapon_ttt_p228', 'P228')
Add(159, 'weapon_ttt_bouncy_kkona', 'Bouncy KKona')
Add(160, 'weapon_ttt_shortgasgrenade', 'Gas Grenade')
Add(161, 'weapon_xmassmoke', 'Christmas Smoke')
Add(162, 'weapon_ttt_mine_turtle', 'Mine Turtle')
Add(163, 'weapon_ttt_aug', 'AUG')
Add(164, 'ai_weapon_sword_ebony', nil)
Add(165, 'ai_weapon_sword_falmer', nil)
Add(166, 'ttt_realistic_hook', 'Grappling Hook')
Add(167, 'weapon_ttt_freezegun', 'Freeze Gun')
Add(168, 'weapon_ttt_baseballbat', 'Baseball Bat')
Add(169, 'weapon_ragingbull', 'Raging Bull')
Add(170, 'ai_weapon_bow_ebony', nil)
Add(171, 'weapon_ttt_mp5k', 'MP5K')
Add(172, 'weapon_virus9mm', 'TAC-45')
Add(173, 'weapon_ttt_taunt_hands', 'Hands Up Taunt')
Add(174, 'weapon_zm_pistol', 'Pistol')
Add(175, 'weapon_ttt_flaregun', 'Flare Gun')
Add(176, 'weapon_ttt_bouncy_suchmeme', 'Bouncy SuchMeme')
Add(177, 'weapon_smartpen', 'Smart Pen')
Add(178, 'weapon_ttt_dual_elites', 'Dual Elites')
Add(179, 'weapon_ttt_bouncy_pogchamp', 'Bouncy PogChamp')
Add(180, 'weapon_ttt_bouncy_4head', 'Bouncy 4Head')
Add(181, 'weapon_ttt_homingbirdtrap', 'Pigeon Bomb')
Add(182, 'weapon_xmasfrag', 'Christmas Frag')
Add(183, 'weapon_ttt_bouncy_kappa', 'Bouncy Kappa')
Add(184, 'weapon_ttt_bouncy_rngplz', 'Bouncy RNGplz')
Add(185, 'weapon_ttt_bouncy_forsencd', 'Bouncy forsenCD')
Add(186, 'weapon_ttt_deliverer', 'The Deliverer')
Add(187, 'weapon_ttt_bouncy_monkaomega', 'Bouncy monkaOMEGA')
Add(188, 'weapon_ttt_candycane', 'A Candy Cane')
Add(189, 'posswitch', 'Position Swapper')
Add(190, 'weapon_ttt_bouncy_monkamega', 'Bouncy monkaMega')
Add(191, 'weapon_ttt_bouncy_waitwhat', 'Bouncy WaitWhat')
Add(192, 'weapon_ttt_m03a3', 'Springfield')
Add(193, 'weapon_ttt_bouncy_pepehands', 'Bouncy PepeHands')
Add(194, 'tnt_fists', 'Fists')
Add(195, 'weapon_ttt_pipewrench', 'Pipe Wrench')
Add(196, 'weapon_ttt_hkusp', 'HK USP')
Add(197, 'weapon_vape_hallucinogenic', 'Hallucinogenic Vape')
Add(198, 'weapon_ttt_bouncy_omegalul', 'Bouncy OMEGALUL')
Add(199, 'weapon_ttt_msbs', 'MSBS')
Add(200, 'weapon_ttt_taunt_bow', 'Bow Taunt')
Add(201, 'weapon_cure', 'Cure')
Add(202, 'ai_weapon_base_melee', nil)
Add(203, 'weapon_diamond_sword', 'Diamond Sword')
Add(204, 'weapon_ttt_m1014', 'M1014')
Add(205, 'weapon_mor_bonemold', 'Bonemold Bow')
Add(206, 'plasmanade', 'Plasma Grenade')
Add(207, 'weapon_ttt_peacekeeper', 'Peacekeeper')
Add(208, 'weapon_elementalbase', 'Elemental Base')
Add(209, 'weapon_ttt_doorbuster', 'Door Buster')
Add(210, 'weapon_ttt_c4', 'C4')
Add(211, 'weapon_ttt_defuser', 'Defuser')
Add(212, 'weapon_ttt_cardboardknife', 'Cardboard Knife')
Add(213, 'weapon_ttt_bouncy_lulw', 'Bouncy LULW')
Add(214, 'weapon_ttt_bouncy_monkagun', 'Bouncy monkaGun')
Add(215, 'weapon_ttt_decoy', 'Decoy')
Add(216, 'weapon_vape_american', 'American Vape')
Add(217, 'weapon_ttt_boomerang', 'Boomerang')
Add(218, 'weapon_ttt_beacon', 'Beacon')
Add(219, 'ai_weapon_axe_battle_draugr', nil)
Add(220, 'weapon_ttt_springmine', 'Spring Mine')
Add(221, 'ai_weapon_base_bow', nil)
Add(222, 'weapon_zm_revolver', 'Deagle')
Add(223, 'weapon_ttt_rsb_defuser', 'RSB Defuser')
Add(224, 'weapon_ttt_predator_blade', 'Predator Blade')
Add(225, 'weapon_akimbo', 'Akimbo Pistols')
Add(226, 'weapon_ttt_ftester', 'Fake Portable Tester')
Add(227, 'weapon_ttt_attack-forcer', 'Attack-Forcer')
Add(228, 'boomer_scoped_base', nil)
Add(229, 'weapon_rcp120', 'RCP-120')
Add(230, 'weapon_vape', 'Vape')
Add(231, 'weapon_ttt_m590', 'Mossberg')
Add(232, 'weapon_ttt_hjump', 'High Jump')
Add(233, 'weapon_ttt_taunt_robot', 'Robot Taunt')
Add(234, 'weapon_spas12pvp', 'SPAS-12')
Add(235, 'weapon_mor_base_bow', 'Steel Bow')
Add(236, 'weapon_ttt_sipistol', 'Silenced Pistol')
Add(237, 'weapon_ttt_awp', 'Silenced AWP')
Add(238, 'ai_weapon_axe_war_falmer', nil)
Add(239, 'weapon_babynade', 'Babynade')
Add(240, 'weapon_thompson', 'Tommy Gun')
Add(241, 'weapon_ttt_sandwich', 'Sandwich')
Add(242, 'weapon_boombody', 'Boom Body')
Add(243, 'weapon_ttt_slam', 'M4 SLAM')
Add(244, 'weapon_ttt_phammer', 'Poltergeist')
Add(245, 'weapon_medkit', 'Medkit')
Add(246, 'weapon_vadim_blink', 'Blink')
Add(247, 'ai_weapon_base_warhammer', nil)
Add(248, 'snowball_hs', 'Snowball')
Add(249, 'weapon_ttt_id_bomb', 'Identification Bomb')
Add(250, 'weapon_diamond_pick', 'Diamond Pickaxe')
Add(251, 'weapon_vape_juicy', 'Juicy Vape')
Add(252, 'weapon_ttt_knifestalker', 'Stalker Knife')
Add(253, 'weapon_supershotty', 'S12')
Add(254, 'weapon_ttt_locker', 'Door Locker')
Add(255, 'weapon_stealthbox', 'Stealth Box')
Add(256, 'weapon_base', 'Scripted Weapon')
Add(257, 'weapon_ttt_m1911', 'M1911')
Add(258, 'ai_weapon_base_axe_battle', nil)
Add(259, 'weapon_toy_hammer', 'Toy Hammer')
Add(260, 'weapon_ttt_p90', 'FN P90')
Add(261, 'weapon_zombie', 'Zombie Hands')
Add(262, 'weapon_ttt_health_station', 'Health Station')
Add(263, 'lava_fists', 'Fists')
Add(264, 'weapon_vape_golden', 'Golden Vape')
Add(265, 'weapon_fireball', 'Fireball')
Add(266, 'weapon_angryhobo', 'Angry Shoe')
Add(267, 'weapon_ttt_taunt_agree', 'Agree Taunt')
Add(268, 'weapon_ttt_taunt_climb', 'Zombie Climb Taunt')
Add(269, 'weapon_ttt_taunt_laugh', 'Laugh Taunt')
Add(270, 'weapon_banana', 'Banana Bomb')
Add(271, 'weapon_vape_helium', 'Helium Vape')
Add(272, 'weapon_ttt_chair', 'A Chair')
Add(273, 'weapon_ttt_te_famas', 'Famas TE')
Add(274, 'weapon_ttt_te_ots33', 'OTS-33')
Add(275, 'weapon_ttt_te_sako', 'Sako')
Add(276, 'weapon_ttt_te_sterlings', 'Sterling Silver')
Add(277, 'weapon_ttt_famas', 'Famas')
Add(278, 'weapon_ttt_occrowbar', 'Mega Crowbar')
Add(279, 'weapon_ttt_te_vollmer', 'MP5G')
Add(280, 'weapon_tttbase', nil)
Add(281, 'weapon_ttt_teleport', 'Teleporter')
Add(282, 'weapon_ttt_golden_deagle', 'Golden Deagle')
Add(283, 'weapon_ttt_thunder_thighs', 'Thunder Thighs')
Add(284, 'weapon_ttt_ump45', 'UMP-45')
Add(285, 'weapon_zm_sledge', 'H.U.G.E-249')
Add(286, 'weapon_ttt_taunt_test', 'Testing Taunt')
Add(287, 'ai_weapon_warhammer_ebony', nil)
Add(288, 'weapon_zm_carry', 'Magneto Stick')