if SERVER then
	AddCSLuaFile()
end

local function AddPlayerModel( name, model, hands )

	list.Set( "PlayerOptionsModel", name, model )
	player_manager.AddValidModel( name, model )

	if hands then
		player_manager.AddValidHands( name, hands, 0, "00000000" )
	end

end

AddPlayerModel( "normal", "models/player/normal.mdl" ) // Used in Duels and PVP Battle!
AddPlayerModel( "teslapower", "models/player/teslapower.mdl" )
AddPlayerModel( "spytf2", "models/player/drpyspy/spy.mdl" )
AddPlayerModel( "shaun", "models/player/shaun.mdl" )
AddPlayerModel( "isaac", "models/player/security_suit.mdl" )
AddPlayerModel( "midna", "models/player/midna.mdl" )
AddPlayerModel( "maskedbreen", "models/player/Sunabouzu.mdl" )
AddPlayerModel( "zoey", "models/player/zoey.mdl" )
AddPlayerModel( "sniper", "models/player/robber.mdl" )
AddPlayerModel( "spacesuit", "models/player/spacesuit.mdl" )
AddPlayerModel( "scarecrow", "models/player/scarecrow.mdl" )
AddPlayerModel( "smith", "models/player/smith.mdl" )
AddPlayerModel( "libertyprime", "models/player/sam.mdl" )
AddPlayerModel( "rpcop", "models/player/azuisleet1.mdl" )
AddPlayerModel( "altair", "models/player/altair.mdl" )
AddPlayerModel( "dinosaur", "models/player/foohysaurusrex.mdl" )
AddPlayerModel( "rorschach", "models/player/rorschach.mdl" )
AddPlayerModel( "aphaztech", "models/player/aphaztech.mdl" )
AddPlayerModel( "faith", "models/player/faith.mdl" )
AddPlayerModel( "robot", "models/player/robot.mdl" )
AddPlayerModel( "niko", "models/player/niko.mdl" )
AddPlayerModel( "zelda", "models/player/zelda.mdl" )
AddPlayerModel( "dude", "models/player/dude.mdl" )
AddPlayerModel( "leon", "models/player/leon.mdl" )
AddPlayerModel( "chris", "models/player/chris.mdl" )
AddPlayerModel( "gmen", "models/player/gmen.mdl" )
AddPlayerModel( "joker", "models/player/joker.mdl" )
AddPlayerModel( "hunter", "models/player/hunter.mdl" )
AddPlayerModel( "steve", "models/player/mcsteve.mdl" )
AddPlayerModel( "gordon", "models/player/gordon.mdl" )
AddPlayerModel( "masseffect", "models/player/masseffect.mdl" )
AddPlayerModel( "scorpion", "models/player/scorpion.mdl" )
AddPlayerModel( "subzero", "models/player/subzero.mdl" )
AddPlayerModel( "undeadcombine", "models/player/clopsy.mdl" )
AddPlayerModel( "boxman", "models/player/nuggets.mdl" )
AddPlayerModel( "classygentleman", "models/player/macdguy.mdl" )
AddPlayerModel( "rayman", "models/player/rayman.mdl" )
AddPlayerModel( "raz", "models/player/raz.mdl" )
AddPlayerModel( "knight", "models/player/knight.mdl" )
AddPlayerModel( "bobafett", "models/player/bobafett.mdl" )
AddPlayerModel( "chewbacca", "models/player/chewbacca.mdl" )
AddPlayerModel( "assassin", "models/player/dishonored_assassin1.mdl" )
AddPlayerModel( "haroldlott", "models/player/haroldlott.mdl" )
AddPlayerModel( "harry_potter", "models/player/harry_potter.mdl" )
AddPlayerModel( "jack_sparrow", "models/player/jack_sparrow.mdl" )
AddPlayerModel( "jawa", "models/player/jawa.mdl" )
AddPlayerModel( "marty", "models/player/martymcfly.mdl" )
AddPlayerModel( "samuszero", "models/player/samusz.mdl" )
AddPlayerModel( "skeleton", "models/player/skeleton.mdl" )
AddPlayerModel( "stormtrooper", "models/player/stormtrooper.mdl" )
AddPlayerModel( "luigi", "models/player/suluigi_galaxy.mdl" )
AddPlayerModel( "mario", "models/player/sumario_galaxy.mdl" )
AddPlayerModel( "zero", "models/player/lordvipes/MMZ/Zero/zero_playermodel_cvp.mdl" )
AddPlayerModel( "yoshi", "models/player/yoshi.mdl" )
AddPlayerModel( "grayfox", "models/player/lordvipes/Metal_Gear_Rising/gray_fox_playermodel_cvp.mdl" )
AddPlayerModel( "crimsonlance", "models/player/lordvipes/bl_clance/crimsonlanceplayer.mdl", "models/player/lordvipes/bl_clance/Arms/crimsonlanceamrs.mdl" )
AddPlayerModel( "walterwhite", "models/Agent_47/agent_47.mdl" )
AddPlayerModel( "jackskellington", "models/vinrax/player/Jack_player.mdl", "models/vinrax/weapons/c_arms_jack.mdl" ) -- by Vinrax
AddPlayerModel( "deadpool", "models/player/deadpool.mdl" )
AddPlayerModel( "deathstroke", "models/norpo/ArkhamOrigins/Assassins/Deathstroke_ValveBiped.mdl", "models/norpo/ArkhamOrigins/Assassins/Viewmodel/Deathstroke_ValveBiped_HandModel.mdl" )
AddPlayerModel( "carley", "models/nikout/carleypm.mdl" )
AddPlayerModel( "solidsnake", "models/player/big_boss.mdl", "models/player/big_boss_hands.mdl" )
AddPlayerModel( "tronanon", "models/player/anon/anon.mdl", "models/weapons/arms/anon_arms.mdl" ) -- by Rokay "Rambo"
AddPlayerModel( "alice", "models/player/alice.mdl" )
AddPlayerModel( "windrunner", "models/heroes/windrunner/windrunner.mdl", "models/heroes/windrunner/c_arms_windrunner.mdl" )
AddPlayerModel( "ash", "models/player/red.mdl" )
AddPlayerModel( "megaman", "models/vinrax/player/megaman64_no_gun_player.mdl" )
AddPlayerModel( "kilik", "models/player/hhp227/kilik.mdl" )
AddPlayerModel( "bond", "models/player/bond.mdl" )
AddPlayerModel( "ironman", "models/Avengers/Iron Man/mark7_player.mdl" )
AddPlayerModel( "masterchief", "models/player/lordvipes/haloce/spartan_classic.mdl" )
AddPlayerModel( "doomguy", "models/ex-mo/quake3/players/doom.mdl" )
AddPlayerModel( "freddykruger", "models/player/freddykruger.mdl" )
AddPlayerModel( "linktp", "models/player/linktp.mdl" )
AddPlayerModel( "roman", "models/player/romanbellic.mdl" )