include ("structs/accountinformation.lua")
include ("structs/debuggetinfofunctioninformation.lua")
include ("structs/functionverificationinformation.lua")
include ("structs/gameinformation.lua")
include ("structs/hardwareinformation.lua")
include ("structs/incident.lua")
include ("structs/jitutilfuncinfofunctioninformation.lua")
include ("structs/locationinformation.lua")
include ("structs/operatingsysteminformation.lua")

