CREATE TABLE IF NOT EXISTS `core_members` (
	`member_id` mediumint(8) NOT NULL AUTO_INCREMENT,
	`name` varchar(255) NOT NULL DEFAULT '',
	`member_group_id` smallint(3) NOT NULL DEFAULT 0,
	`email` varchar(150) NOT NULL DEFAULT '',
	`joined` int(10) NOT NULL DEFAULT 0,
	`ip_address` varchar(46) NOT NULL DEFAULT '',
	`skin` smallint(5) DEFAULT NULL,
	`warn_level` int(10) DEFAULT NULL,
	`warn_lastwarn` int(10) NOT NULL DEFAULT 0,
	`language` mediumint(4) DEFAULT NULL,
	`restrict_post` int(10) NOT NULL DEFAULT 0,
	`bday_day` int(2) DEFAULT NULL,
	`bday_month` int(2) DEFAULT NULL,
	`bday_year` int(4) DEFAULT NULL,
	`msg_count_new` int(2) NOT NULL DEFAULT 0,
	`msg_count_total` int(3) NOT NULL DEFAULT 0,
	`msg_count_reset` int(1) NOT NULL DEFAULT 0,
	`msg_show_notification` int(1) NOT NULL DEFAULT 0,
	`last_visit` int(10) DEFAULT 0,
	`last_activity` int(10) DEFAULT 0,
	`mod_posts` int(10) NOT NULL DEFAULT 0,
	`auto_track` varchar(255) DEFAULT '0',
	`temp_ban` int(10) DEFAULT 0,
	`mgroup_others` varchar(245) NOT NULL DEFAULT '',
	`member_login_key_expire` int(10) NOT NULL DEFAULT 0,
	`members_seo_name` varchar(255) NOT NULL DEFAULT '',
	`members_cache` mediumtext DEFAULT NULL,
	`failed_logins` text DEFAULT NULL,
	`failed_login_count` smallint(3) NOT NULL DEFAULT 0,
	`members_profile_views` int(10) unsigned NOT NULL DEFAULT 0,
	`members_pass_hash` varchar(255) DEFAULT NULL,
	`members_pass_salt` varchar(22) DEFAULT NULL,
	`members_bitoptions` int(10) unsigned NOT NULL DEFAULT 0,
	`fb_uid` bigint(20) unsigned NOT NULL DEFAULT 0,
	`members_day_posts` varchar(32) NOT NULL DEFAULT '0,0',
	`live_id` varchar(32) DEFAULT NULL,
	`twitter_id` varchar(255) NOT NULL DEFAULT '',
	`twitter_token` varchar(255) NOT NULL DEFAULT '',
	`twitter_secret` varchar(255) NOT NULL DEFAULT '',
	`notification_cnt` mediumint(9) NOT NULL DEFAULT 0,
	`fb_token` text DEFAULT NULL,
	`ipsconnect_id` int(10) NOT NULL DEFAULT 0,
	`google_id` varchar(50) DEFAULT NULL,
	`linkedin_id` varchar(32) DEFAULT NULL,
	`pp_last_visitors` text DEFAULT NULL,
	`pp_main_photo` text DEFAULT NULL,
	`pp_main_width` int(5) DEFAULT NULL,
	`pp_main_height` int(5) DEFAULT NULL,
	`pp_thumb_photo` text DEFAULT NULL,
	`pp_thumb_width` int(5) DEFAULT NULL,
	`pp_thumb_height` int(5) DEFAULT NULL,
	`pp_setting_count_comments` int(2) DEFAULT NULL,
	`pp_reputation_points` int(10) DEFAULT NULL,
	`pp_photo_type` varchar(20) DEFAULT NULL,
	`signature` text DEFAULT NULL,
	`pconversation_filters` text DEFAULT NULL,
	`fb_photo` text DEFAULT NULL,
	`fb_photo_thumb` text DEFAULT NULL,
	`fb_bwoptions` int(10) DEFAULT NULL,
	`tc_last_sid_import` varchar(50) DEFAULT NULL,
	`tc_photo` text DEFAULT NULL,
	`tc_bwoptions` int(10) DEFAULT NULL,
	`pp_customization` mediumtext DEFAULT NULL,
	`timezone` varchar(64) DEFAULT NULL,
	`pp_cover_photo` varchar(255) NOT NULL DEFAULT '',
	`profilesync` text DEFAULT NULL,
	`profilesync_lastsync` int(10) NOT NULL DEFAULT 0 COMMENT 'Indicates the last time any profile sync service was ran',
	`google_token` text DEFAULT NULL,
	`linkedin_token` text DEFAULT NULL,
	`live_token` text DEFAULT NULL,
	`allow_admin_mails` bit(1) DEFAULT b'0',
	`members_bitoptions2` int(10) unsigned NOT NULL DEFAULT 0,
	`create_menu` text DEFAULT NULL COMMENT 'Cached contents of the "Create" drop down menu.',
	`ipsconnect_revalidate_url` text DEFAULT NULL,
	`members_disable_pm` tinyint(1) unsigned NOT NULL DEFAULT 0 COMMENT '0 - not disabled, 1 - disabled, member can re-enable, 2 - disabled',
	`marked_site_read` int(10) unsigned DEFAULT 0,
	`pp_cover_offset` int(10) NOT NULL DEFAULT 0,
	`acp_skin` smallint(6) DEFAULT NULL,
	`acp_language` mediumint(9) DEFAULT NULL,
	`member_title` varchar(64) DEFAULT NULL,
	`member_posts` mediumint(7) NOT NULL DEFAULT 0,
	`member_last_post` int(10) DEFAULT NULL,
	`member_streams` text DEFAULT NULL,
	`photo_last_update` int(10) DEFAULT NULL,
	`steamid` varchar(17) DEFAULT NULL,
	`kuzi_song_path` varchar(255) DEFAULT '' COMMENT 'Profile song path.',
	`failed_mfa_attempts` smallint(3) unsigned DEFAULT 0 COMMENT 'Number of times tried and failed MFA',
	`unlucky_enable` int(1) DEFAULT 0,
	`unlucky_url` varchar(255) DEFAULT '',
	`mfa_details` text DEFAULT NULL,
	`permission_array` text DEFAULT NULL COMMENT 'A cache of the clubs and social groups that the member is in',
	`discord_id` varchar(20) DEFAULT NULL,
	`discord_name` varchar(50) DEFAULT NULL,
	`account_closed` tinyint(1) unsigned DEFAULT 0,
	`account_closed_reason` text DEFAULT NULL,
	`autoreplypm_on` tinyint(1) DEFAULT 0,
	`autoreplypm_text` text DEFAULT NULL,
	`nbcontentratings_positive` int(10) unsigned DEFAULT NULL,
	`nbcontentratings_negative` int(10) unsigned DEFAULT NULL,
	`nbcontentratings_neutral` int(10) unsigned DEFAULT NULL,
	`tm_member_tracked` tinyint(1) NOT NULL DEFAULT 0,
	`tm_member_tracked_deadline` int(10) NOT NULL DEFAULT 0,
	`tm_member_tracked_log_entries` int(10) NOT NULL DEFAULT 0,
	`tm_member_tracked_actions` text DEFAULT NULL,
	`completed` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Whether the account is completed or not',
	`conv_password` varchar(255) DEFAULT NULL,
	`conv_password_extra` varchar(255) DEFAULT NULL,
	`membermap_location_synced` tinyint(1) DEFAULT 0,
	`cm_credits` text DEFAULT NULL,
	`cm_no_sev` tinyint(1) DEFAULT 0,
	`cm_return_group` smallint(3) DEFAULT 0,
	`idm_block_submissions` tinyint(1) unsigned DEFAULT 0 COMMENT 'Blocked from submitting Downloads files?',
	PRIMARY KEY (`member_id`),
	UNIQUE KEY `discord_id` (`discord_id`),
	KEY `bday_day` (`bday_day`),
	KEY `bday_month` (`bday_month`),
	KEY `members_bitoptions` (`members_bitoptions`),
	KEY `ip_address` (`ip_address`),
	KEY `failed_login_count` (`failed_login_count`),
	KEY `joined` (`joined`),
	KEY `fb_uid` (`fb_uid`),
	KEY `twitter_id` (`twitter_id`(191)),
	KEY `email` (`email`),
	KEY `member_groups` (`member_group_id`,`mgroup_others`(188)),
	KEY `google_id` (`google_id`),
	KEY `linkedin_id` (`linkedin_id`),
	KEY `mgroup` (`member_id`,`member_group_id`),
	KEY `allow_admin_mails` (`allow_admin_mails`),
	KEY `name_index` (`name`(191)),
	KEY `ipsconnect_id` (`ipsconnect_id`),
	KEY `mod_posts` (`mod_posts`),
	KEY `photo_last_update` (`photo_last_update`),
	KEY `steamid` (`steamid`),
	KEY `last_activity` (`last_activity`),
	KEY `completed` (`completed`,`temp_ban`),
	KEY `profilesync` (`profilesync_lastsync`,`profilesync`(150))
);