local df = system.IsLinux() and 'DejaVu Sans' or 'Tahoma'
_SCF('acrashscreen_small', {font = 'Arial',size = 28,weight = 900})
_SCF('acrashscreen_medium', {font = 'Arial',size = 32,weight = 900})
_SCF('acrashscreen_big', {font = 'Arial',size = 36,weight = 900})
_SCF('DermaLargeSmall', {font = df,weight = 500,size = 18})
_SCF('DermaLargeSmall2', {font = df,weight = 500,size = 16})
_SCF('DermaLargeSmall3', {font = df,weight = 500,size = 12})
_SCF('DermaLargeSmall_', {font = df,size = 18,weight = 800})
_SCF('DermaLargeSmall2_', {font = df,size = 16,weight = 800})
_SCF('DermaLargeSmall3_', {font = df,size = 12,weight = 700})
_SCF('M_DL_ChatCategory', {font = df,size = 17,weight = 700})
_SCF('M_DL_ChatFont', {font = df,size = 17})
_SCF('M_DL_ChatPlayer', {font = df,size = 16,weight = 600})
_SCF('RDM_Manager_Player', {font = df,weight = 500,size = 17})
_SCF('M_DL_Highlight', {font = 'Verdana',size = 13})
_SCF('M_DL_OldLogsFont', {font = df,weight = 500,size = 20})
_SCF('M_DL_RDM_Manager', {font = df,weight = 500,size = 20})
_SCF('M_DL_Conclusion', {font = df,size = 18,weight = 600})
_SCF('M_DL_ConclusionText', {font = df,weight = 500,size = 18})
_SCF('M_DL_ResponseDisabled', {font = df,weight = 500,size = 16})
_SCF('RAM_VoteFont', {font = 'Trebuchet MS',size = 19,weight = 700,shadow = true})
_SCF('RAM_VoteFontCountdown', {font = df,size = 32,weight = 700,shadow = true})
_SCF('RAM_VoteSysButton', {font = 'Marlett',size = 13,weight = 0,symbol = true})
_SCF('moat_Feedback', {font = 'Roboto',size = 20,weight = 500})
_SCF('moat_mVotes', {font = df,size = 30,weight = 800})
_SCF('moat_mFeed', {font = df,size = 22,weight = 1000})
_SCF('moat_mTitle', {font = df,size = 22,weight = 800})
_SCF('moat_BossWarning', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_BossInfo', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_BossInfo2', {font = df,size = 18,weight = 800,italic = true})
_SCF('moat_BossWarning', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_BossInfo', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_BossInfo2', {font = df,size = 18,weight = 800,italic = true})
_SCF('moat_BossWarning', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_BossInfo', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_BossInfo2', {font = df,size = 18,weight = 800,italic = true})
_SCF('moat_BossWarning', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_TDMLead1', {font = df,size = 21,weight = 800,italic = true})
_SCF('moat_TDMLead2', {font = df,size = 22,weight = 800,italic = true})
_SCF('moat_TDMLead3', {font = df,size = 23,weight = 800,italic = true})
_SCF('moat_TDMLead4', {font = df,size = 24,weight = 800,italic = true})
_SCF('moat_TDMLead5', {font = df,size = 25,weight = 800,italic = true})
_SCF('moat_TDMLead6', {font = df,size = 26,weight = 800,italic = true})
_SCF('moat_TDMLead7', {font = df,size = 27,weight = 800,italic = true})
_SCF('moat_TDMLead8', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_TDMLead9', {font = df,size = 29,weight = 800,italic = true})
_SCF('moat_TDMLead10', {font = df,size = 30,weight = 800,italic = true})
_SCF('moat_TDMLead11', {font = df,size = 31,weight = 800,italic = true})
_SCF('moat_TDMLead12', {font = df,size = 32,weight = 800,italic = true})
_SCF('moat_TDMLead13', {font = df,size = 33,weight = 800,italic = true})
_SCF('moat_TDMLead14', {font = df,size = 34,weight = 800,italic = true})
_SCF('moat_TDMLead15', {font = df,size = 35,weight = 800,italic = true})
_SCF('moat_TDMLead16', {font = df,size = 36,weight = 800,italic = true})
_SCF('moat_TDMLead17', {font = df,size = 37,weight = 800,italic = true})
_SCF('moat_TDMLead18', {font = df,size = 38,weight = 800,italic = true})
_SCF('moat_TDMLead19', {font = df,size = 39,weight = 800,italic = true})
_SCF('moat_TDMLead20', {font = df,size = 40,weight = 800,italic = true})
_SCF('moat_TDMLead21', {font = df,size = 41,weight = 800,italic = true})
_SCF('moat_TDMLead22', {font = df,size = 42,weight = 800,italic = true})
_SCF('moat_TDMLead23', {font = df,size = 43,weight = 800,italic = true})
_SCF('moat_TDMLead24', {font = df,size = 44,weight = 800,italic = true})
_SCF('moat_TDMLead25', {font = df,size = 45,weight = 800,italic = true})
_SCF('moat_GunGameMedium', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_GunGameSmall', {font = df,size = 18,weight = 800})
_SCF('moat_GunGameLarge', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_BossWarning', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_FFALead1', {font = df,size = 21,weight = 800,italic = true})
_SCF('moat_FFALead2', {font = df,size = 22,weight = 800,italic = true})
_SCF('moat_FFALead3', {font = df,size = 23,weight = 800,italic = true})
_SCF('moat_FFALead4', {font = df,size = 24,weight = 800,italic = true})
_SCF('moat_FFALead5', {font = df,size = 25,weight = 800,italic = true})
_SCF('moat_FFALead6', {font = df,size = 26,weight = 800,italic = true})
_SCF('moat_FFALead7', {font = df,size = 27,weight = 800,italic = true})
_SCF('moat_FFALead8', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_FFALead9', {font = df,size = 29,weight = 800,italic = true})
_SCF('moat_FFALead10', {font = df,size = 30,weight = 800,italic = true})
_SCF('moat_FFALead11', {font = df,size = 31,weight = 800,italic = true})
_SCF('moat_FFALead12', {font = df,size = 32,weight = 800,italic = true})
_SCF('moat_FFALead13', {font = df,size = 33,weight = 800,italic = true})
_SCF('moat_FFALead14', {font = df,size = 34,weight = 800,italic = true})
_SCF('moat_FFALead15', {font = df,size = 35,weight = 800,italic = true})
_SCF('moat_FFALead16', {font = df,size = 36,weight = 800,italic = true})
_SCF('moat_FFALead17', {font = df,size = 37,weight = 800,italic = true})
_SCF('moat_FFALead18', {font = df,size = 38,weight = 800,italic = true})
_SCF('moat_FFALead19', {font = df,size = 39,weight = 800,italic = true})
_SCF('moat_FFALead20', {font = df,size = 40,weight = 800,italic = true})
_SCF('moat_FFALead21', {font = df,size = 41,weight = 800,italic = true})
_SCF('moat_FFALead22', {font = df,size = 42,weight = 800,italic = true})
_SCF('moat_FFALead23', {font = df,size = 43,weight = 800,italic = true})
_SCF('moat_FFALead24', {font = df,size = 44,weight = 800,italic = true})
_SCF('moat_FFALead25', {font = df,size = 45,weight = 800,italic = true})
_SCF('moat_FFALead26', {font = df,size = 46,weight = 800,italic = true})
_SCF('moat_FFALead27', {font = df,size = 47,weight = 800,italic = true})
_SCF('moat_FFALead28', {font = df,size = 48,weight = 800,italic = true})
_SCF('moat_FFALead29', {font = df,size = 49,weight = 800,italic = true})
_SCF('moat_FFALead30', {font = df,size = 50,weight = 800,italic = true})
_SCF('moat_FFALead31', {font = df,size = 51,weight = 800,italic = true})
_SCF('moat_FFALead32', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_FFALead33', {font = df,size = 53,weight = 800,italic = true})
_SCF('moat_FFALead34', {font = df,size = 54,weight = 800,italic = true})
_SCF('moat_FFALead35', {font = df,size = 55,weight = 800,italic = true})
_SCF('moat_FFALead36', {font = df,size = 56,weight = 800,italic = true})
_SCF('moat_FFALead37', {font = df,size = 57,weight = 800,italic = true})
_SCF('moat_FFALead38', {font = df,size = 58,weight = 800,italic = true})
_SCF('moat_FFALead39', {font = df,size = 59,weight = 800,italic = true})
_SCF('moat_FFALead40', {font = df,size = 60,weight = 800,italic = true})
_SCF('moat_FFALead41', {font = df,size = 61,weight = 800,italic = true})
_SCF('moat_FFALead42', {font = df,size = 62,weight = 800,italic = true})
_SCF('moat_FFALead43', {font = df,size = 63,weight = 800,italic = true})
_SCF('moat_FFALead44', {font = df,size = 64,weight = 800,italic = true})
_SCF('moat_FFALead45', {font = df,size = 65,weight = 800,italic = true})
_SCF('moat_FFALead46', {font = df,size = 66,weight = 800,italic = true})
_SCF('moat_FFALead47', {font = df,size = 67,weight = 800,italic = true})
_SCF('moat_FFALead48', {font = df,size = 68,weight = 800,italic = true})
_SCF('moat_FFALead49', {font = df,size = 69,weight = 800,italic = true})
_SCF('moat_FFALead50', {font = df,size = 70,weight = 800,italic = true})
_SCF('moat_GunGameMedium', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_GunGameSmall', {font = df,size = 18,weight = 800})
_SCF('moat_GunGameLarge', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_GunGameMedium', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_GunGameSmall', {font = df,size = 18,weight = 800})
_SCF('moat_GunGameLarge', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_GunGameMedium', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_GunGameSmall', {font = df,size = 18,weight = 800})
_SCF('moat_GunGameLarge', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_GunGameMedium', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_GunGameSmall', {font = df,size = 18,weight = 800})
_SCF('moat_GunGameLarge', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_BossWarning', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_BossInfo', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_BossInfo2', {font = df,size = 18,weight = 800,italic = true})
_SCF('moat_GunGameMedium', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_GunGameSmall', {font = df,size = 18,weight = 800})
_SCF('moat_GunGameLarge', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_BossWarning', {font = df,size = 52,weight = 800,italic = true})
_SCF('MOAT_LAVALead1', {font = df,size = 21,weight = 800,italic = true})
_SCF('MOAT_LAVALead2', {font = df,size = 22,weight = 800,italic = true})
_SCF('MOAT_LAVALead3', {font = df,size = 23,weight = 800,italic = true})
_SCF('MOAT_LAVALead4', {font = df,size = 24,weight = 800,italic = true})
_SCF('MOAT_LAVALead5', {font = df,size = 25,weight = 800,italic = true})
_SCF('MOAT_LAVALead6', {font = df,size = 26,weight = 800,italic = true})
_SCF('MOAT_LAVALead7', {font = df,size = 27,weight = 800,italic = true})
_SCF('MOAT_LAVALead8', {font = df,size = 28,weight = 800,italic = true})
_SCF('MOAT_LAVALead9', {font = df,size = 29,weight = 800,italic = true})
_SCF('MOAT_LAVALead10', {font = df,size = 30,weight = 800,italic = true})
_SCF('MOAT_LAVALead11', {font = df,size = 31,weight = 800,italic = true})
_SCF('MOAT_LAVALead12', {font = df,size = 32,weight = 800,italic = true})
_SCF('MOAT_LAVALead13', {font = df,size = 33,weight = 800,italic = true})
_SCF('MOAT_LAVALead14', {font = df,size = 34,weight = 800,italic = true})
_SCF('MOAT_LAVALead15', {font = df,size = 35,weight = 800,italic = true})
_SCF('MOAT_LAVALead16', {font = df,size = 36,weight = 800,italic = true})
_SCF('MOAT_LAVALead17', {font = df,size = 37,weight = 800,italic = true})
_SCF('MOAT_LAVALead18', {font = df,size = 38,weight = 800,italic = true})
_SCF('MOAT_LAVALead19', {font = df,size = 39,weight = 800,italic = true})
_SCF('MOAT_LAVALead20', {font = df,size = 40,weight = 800,italic = true})
_SCF('MOAT_LAVALead21', {font = df,size = 41,weight = 800,italic = true})
_SCF('MOAT_LAVALead22', {font = df,size = 42,weight = 800,italic = true})
_SCF('MOAT_LAVALead23', {font = df,size = 43,weight = 800,italic = true})
_SCF('MOAT_LAVALead24', {font = df,size = 44,weight = 800,italic = true})
_SCF('MOAT_LAVALead25', {font = df,size = 45,weight = 800,italic = true})
_SCF('MOAT_LAVALead26', {font = df,size = 46,weight = 800,italic = true})
_SCF('MOAT_LAVALead27', {font = df,size = 47,weight = 800,italic = true})
_SCF('MOAT_LAVALead28', {font = df,size = 48,weight = 800,italic = true})
_SCF('MOAT_LAVALead29', {font = df,size = 49,weight = 800,italic = true})
_SCF('MOAT_LAVALead30', {font = df,size = 50,weight = 800,italic = true})
_SCF('MOAT_LAVALead31', {font = df,size = 51,weight = 800,italic = true})
_SCF('MOAT_LAVALead32', {font = df,size = 52,weight = 800,italic = true})
_SCF('MOAT_LAVALead33', {font = df,size = 53,weight = 800,italic = true})
_SCF('MOAT_LAVALead34', {font = df,size = 54,weight = 800,italic = true})
_SCF('MOAT_LAVALead35', {font = df,size = 55,weight = 800,italic = true})
_SCF('MOAT_LAVALead36', {font = df,size = 56,weight = 800,italic = true})
_SCF('MOAT_LAVALead37', {font = df,size = 57,weight = 800,italic = true})
_SCF('MOAT_LAVALead38', {font = df,size = 58,weight = 800,italic = true})
_SCF('MOAT_LAVALead39', {font = df,size = 59,weight = 800,italic = true})
_SCF('MOAT_LAVALead40', {font = df,size = 60,weight = 800,italic = true})
_SCF('MOAT_LAVALead41', {font = df,size = 61,weight = 800,italic = true})
_SCF('MOAT_LAVALead42', {font = df,size = 62,weight = 800,italic = true})
_SCF('MOAT_LAVALead43', {font = df,size = 63,weight = 800,italic = true})
_SCF('MOAT_LAVALead44', {font = df,size = 64,weight = 800,italic = true})
_SCF('MOAT_LAVALead45', {font = df,size = 65,weight = 800,italic = true})
_SCF('MOAT_LAVALead46', {font = df,size = 66,weight = 800,italic = true})
_SCF('MOAT_LAVALead47', {font = df,size = 67,weight = 800,italic = true})
_SCF('MOAT_LAVALead48', {font = df,size = 68,weight = 800,italic = true})
_SCF('MOAT_LAVALead49', {font = df,size = 69,weight = 800,italic = true})
_SCF('MOAT_LAVALead50', {font = df,size = 70,weight = 800,italic = true})
_SCF('moat_GunGameMedium', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_GunGameSmall', {font = df,size = 18,weight = 800})
_SCF('moat_GunGameLarge', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_BossWarning', {font = df,size = 52,weight = 800,italic = true})
_SCF('MOAT_TNTLead1', {font = df,size = 21,weight = 800,italic = true})
_SCF('MOAT_TNTLead2', {font = df,size = 22,weight = 800,italic = true})
_SCF('MOAT_TNTLead3', {font = df,size = 23,weight = 800,italic = true})
_SCF('MOAT_TNTLead4', {font = df,size = 24,weight = 800,italic = true})
_SCF('MOAT_TNTLead5', {font = df,size = 25,weight = 800,italic = true})
_SCF('MOAT_TNTLead6', {font = df,size = 26,weight = 800,italic = true})
_SCF('MOAT_TNTLead7', {font = df,size = 27,weight = 800,italic = true})
_SCF('MOAT_TNTLead8', {font = df,size = 28,weight = 800,italic = true})
_SCF('MOAT_TNTLead9', {font = df,size = 29,weight = 800,italic = true})
_SCF('MOAT_TNTLead10', {font = df,size = 30,weight = 800,italic = true})
_SCF('MOAT_TNTLead11', {font = df,size = 31,weight = 800,italic = true})
_SCF('MOAT_TNTLead12', {font = df,size = 32,weight = 800,italic = true})
_SCF('MOAT_TNTLead13', {font = df,size = 33,weight = 800,italic = true})
_SCF('MOAT_TNTLead14', {font = df,size = 34,weight = 800,italic = true})
_SCF('MOAT_TNTLead15', {font = df,size = 35,weight = 800,italic = true})
_SCF('MOAT_TNTLead16', {font = df,size = 36,weight = 800,italic = true})
_SCF('MOAT_TNTLead17', {font = df,size = 37,weight = 800,italic = true})
_SCF('MOAT_TNTLead18', {font = df,size = 38,weight = 800,italic = true})
_SCF('MOAT_TNTLead19', {font = df,size = 39,weight = 800,italic = true})
_SCF('MOAT_TNTLead20', {font = df,size = 40,weight = 800,italic = true})
_SCF('MOAT_TNTLead21', {font = df,size = 41,weight = 800,italic = true})
_SCF('MOAT_TNTLead22', {font = df,size = 42,weight = 800,italic = true})
_SCF('MOAT_TNTLead23', {font = df,size = 43,weight = 800,italic = true})
_SCF('MOAT_TNTLead24', {font = df,size = 44,weight = 800,italic = true})
_SCF('MOAT_TNTLead25', {font = df,size = 45,weight = 800,italic = true})
_SCF('MOAT_TNTLead26', {font = df,size = 46,weight = 800,italic = true})
_SCF('MOAT_TNTLead27', {font = df,size = 47,weight = 800,italic = true})
_SCF('MOAT_TNTLead28', {font = df,size = 48,weight = 800,italic = true})
_SCF('MOAT_TNTLead29', {font = df,size = 49,weight = 800,italic = true})
_SCF('MOAT_TNTLead30', {font = df,size = 50,weight = 800,italic = true})
_SCF('MOAT_TNTLead31', {font = df,size = 51,weight = 800,italic = true})
_SCF('MOAT_TNTLead32', {font = df,size = 52,weight = 800,italic = true})
_SCF('MOAT_TNTLead33', {font = df,size = 53,weight = 800,italic = true})
_SCF('MOAT_TNTLead34', {font = df,size = 54,weight = 800,italic = true})
_SCF('MOAT_TNTLead35', {font = df,size = 55,weight = 800,italic = true})
_SCF('MOAT_TNTLead36', {font = df,size = 56,weight = 800,italic = true})
_SCF('MOAT_TNTLead37', {font = df,size = 57,weight = 800,italic = true})
_SCF('MOAT_TNTLead38', {font = df,size = 58,weight = 800,italic = true})
_SCF('MOAT_TNTLead39', {font = df,size = 59,weight = 800,italic = true})
_SCF('MOAT_TNTLead40', {font = df,size = 60,weight = 800,italic = true})
_SCF('MOAT_TNTLead41', {font = df,size = 61,weight = 800,italic = true})
_SCF('MOAT_TNTLead42', {font = df,size = 62,weight = 800,italic = true})
_SCF('MOAT_TNTLead43', {font = df,size = 63,weight = 800,italic = true})
_SCF('MOAT_TNTLead44', {font = df,size = 64,weight = 800,italic = true})
_SCF('MOAT_TNTLead45', {font = df,size = 65,weight = 800,italic = true})
_SCF('MOAT_TNTLead46', {font = df,size = 66,weight = 800,italic = true})
_SCF('MOAT_TNTLead47', {font = df,size = 67,weight = 800,italic = true})
_SCF('MOAT_TNTLead48', {font = df,size = 68,weight = 800,italic = true})
_SCF('MOAT_TNTLead49', {font = df,size = 69,weight = 800,italic = true})
_SCF('MOAT_TNTLead50', {font = df,size = 70,weight = 800,italic = true})
_SCF('TNT.Big', {font = 'Coolvetica',size = 50,weight = 800,blursize = 0})
_SCF('TNT.Small', {font = 'Coolvetica',size = 30,weight = 800,blursize = 0})
_SCF('moat_GunGameMedium', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_GunGameSmall', {font = df,size = 18,weight = 800})
_SCF('moat_GunGameLarge', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_BossWarning', {font = df,size = 52,weight = 800,italic = true})
_SCF('MOAT_PHLead1', {font = df,size = 21,weight = 800,italic = true})
_SCF('MOAT_PHLead2', {font = df,size = 22,weight = 800,italic = true})
_SCF('MOAT_PHLead3', {font = df,size = 23,weight = 800,italic = true})
_SCF('MOAT_PHLead4', {font = df,size = 24,weight = 800,italic = true})
_SCF('MOAT_PHLead5', {font = df,size = 25,weight = 800,italic = true})
_SCF('MOAT_PHLead6', {font = df,size = 26,weight = 800,italic = true})
_SCF('MOAT_PHLead7', {font = df,size = 27,weight = 800,italic = true})
_SCF('MOAT_PHLead8', {font = df,size = 28,weight = 800,italic = true})
_SCF('MOAT_PHLead9', {font = df,size = 29,weight = 800,italic = true})
_SCF('MOAT_PHLead10', {font = df,size = 30,weight = 800,italic = true})
_SCF('MOAT_PHLead11', {font = df,size = 31,weight = 800,italic = true})
_SCF('MOAT_PHLead12', {font = df,size = 32,weight = 800,italic = true})
_SCF('MOAT_PHLead13', {font = df,size = 33,weight = 800,italic = true})
_SCF('MOAT_PHLead14', {font = df,size = 34,weight = 800,italic = true})
_SCF('MOAT_PHLead15', {font = df,size = 35,weight = 800,italic = true})
_SCF('MOAT_PHLead16', {font = df,size = 36,weight = 800,italic = true})
_SCF('MOAT_PHLead17', {font = df,size = 37,weight = 800,italic = true})
_SCF('MOAT_PHLead18', {font = df,size = 38,weight = 800,italic = true})
_SCF('MOAT_PHLead19', {font = df,size = 39,weight = 800,italic = true})
_SCF('MOAT_PHLead20', {font = df,size = 40,weight = 800,italic = true})
_SCF('MOAT_PHLead21', {font = df,size = 41,weight = 800,italic = true})
_SCF('MOAT_PHLead22', {font = df,size = 42,weight = 800,italic = true})
_SCF('MOAT_PHLead23', {font = df,size = 43,weight = 800,italic = true})
_SCF('MOAT_PHLead24', {font = df,size = 44,weight = 800,italic = true})
_SCF('MOAT_PHLead25', {font = df,size = 45,weight = 800,italic = true})
_SCF('MOAT_PHLead26', {font = df,size = 46,weight = 800,italic = true})
_SCF('MOAT_PHLead27', {font = df,size = 47,weight = 800,italic = true})
_SCF('MOAT_PHLead28', {font = df,size = 48,weight = 800,italic = true})
_SCF('MOAT_PHLead29', {font = df,size = 49,weight = 800,italic = true})
_SCF('MOAT_PHLead30', {font = df,size = 50,weight = 800,italic = true})
_SCF('MOAT_PHLead31', {font = df,size = 51,weight = 800,italic = true})
_SCF('MOAT_PHLead32', {font = df,size = 52,weight = 800,italic = true})
_SCF('MOAT_PHLead33', {font = df,size = 53,weight = 800,italic = true})
_SCF('MOAT_PHLead34', {font = df,size = 54,weight = 800,italic = true})
_SCF('MOAT_PHLead35', {font = df,size = 55,weight = 800,italic = true})
_SCF('MOAT_PHLead36', {font = df,size = 56,weight = 800,italic = true})
_SCF('MOAT_PHLead37', {font = df,size = 57,weight = 800,italic = true})
_SCF('MOAT_PHLead38', {font = df,size = 58,weight = 800,italic = true})
_SCF('MOAT_PHLead39', {font = df,size = 59,weight = 800,italic = true})
_SCF('MOAT_PHLead40', {font = df,size = 60,weight = 800,italic = true})
_SCF('MOAT_PHLead41', {font = df,size = 61,weight = 800,italic = true})
_SCF('MOAT_PHLead42', {font = df,size = 62,weight = 800,italic = true})
_SCF('MOAT_PHLead43', {font = df,size = 63,weight = 800,italic = true})
_SCF('MOAT_PHLead44', {font = df,size = 64,weight = 800,italic = true})
_SCF('MOAT_PHLead45', {font = df,size = 65,weight = 800,italic = true})
_SCF('MOAT_PHLead46', {font = df,size = 66,weight = 800,italic = true})
_SCF('MOAT_PHLead47', {font = df,size = 67,weight = 800,italic = true})
_SCF('MOAT_PHLead48', {font = df,size = 68,weight = 800,italic = true})
_SCF('MOAT_PHLead49', {font = df,size = 69,weight = 800,italic = true})
_SCF('MOAT_PHLead50', {font = df,size = 70,weight = 800,italic = true})
_SCF('PH.Big', {font = 'Coolvetica',size = 50,weight = 800,blursize = 0})
_SCF('PH.Small', {font = 'Coolvetica',size = 30,weight = 800,blursize = 0})
_SCF('moat_GunGameMedium', {font = df,size = 28,weight = 800,italic = true})
_SCF('moat_GunGameSmall', {font = df,size = 18,weight = 800})
_SCF('moat_GunGameLarge', {font = df,size = 52,weight = 800,italic = true})
_SCF('moat_ChatFont', {font = 'Arial',size = 16,weight = 1200})
_SCF('moat_NotifyTest2', {font = df,size = 32,weight = 800})
_SCF('moat_NotifyTestBonus', {font = df,size = 26,weight = 800})
_SCF('moat_Derma1', {font = df,size = 17,weight = 700})
_SCF('moat_Derma2', {font = df,size = 18,weight = 700})
_SCF('moat_Derma3', {font = df,size = 19,weight = 700})
_SCF('moat_Derma4', {font = df,size = 20,weight = 700})
_SCF('moat_Derma5', {font = df,size = 21,weight = 700})
_SCF('moat_Derma6', {font = df,size = 22,weight = 700})
_SCF('moat_Derma7', {font = df,size = 23,weight = 700})
_SCF('moat_Derma8', {font = df,size = 24,weight = 700})
_SCF('moat_Derma9', {font = df,size = 25,weight = 700})
_SCF('moat_Derma10', {font = df,size = 26,weight = 700})
_SCF('moat_LabelFont', {font = df,size = 16,weight = 1200})
_SCF('moat_HitNumberFont', {font = df,size = 200,weight = 700})
_SCF('moat_Medium11', {font = df,size = 28,weight = 800})
_SCF('moat_Trebuchet', {font = df,size = 24,weight = 600})
_SCF('moat_Medium9', {font = df,size = 13,weight = 800})
_SCF('moat_Medium10', {font = df,size = 15,weight = 800})
_SCF('moat_Medium4', {font = df,size = 18,weight = 800})
_SCF('moat_Medium5', {font = df,size = 20,weight = 800})
_SCF('moat_Medium3', {font = df,size = 16,weight = 700})
_SCF('moat_ItemDesc', {font = df,size = 14,weight = 800})
_SCF('moat_TradeDesc', {font = df,size = 12,weight = 800})
_SCF('moat_ItemDescLarge3', {font = df,size = 28,weight = 800})
_SCF('moat_MOTDHead', {font = df,size = 40,weight = 700})
_SCF('moat_ItemDescSmall2', {font = df,size = 10,weight = 700})
_SCF('moat_Medium2', {font = df,size = 12,weight = 500,italic = true})
_SCF('moat_Medium52', {font = df,size = 20,weight = 800,antialias = false})
_SCF('moat_ExtremeLarge', {font = df,size = 200,weight = 800})
_SCF('moat_Extreme1Large', {font = df,size = 100,weight = 800})
_SCF('MinnLottery', {font = df,size = 25,weight = 400})
_SCF('moat_GambleTitle', {font = df,size = 22,weight = 800})
_SCF('moat_CardFont', {font = df,size = 14,weight = 800})
_SCF('moat_DiceWin', {font = df,size = 48,weight = 600})
_SCF('moat_RouletteAmount', {font = df,size = 30,weight = 800})
_SCF('moat_RoulettTime', {font = df,size = 50,weight = 800})
_SCF('moat_RoulettRoll', {font = df,size = 26,weight = 1200})
_SCF('moat_RoulettBet', {font = df,size = 17,weight = 800})
_SCF('moat_crashRoll', {font = df,size = 50,weight = 800})
_SCF('moat_crash', {font = df,size = 40,weight = 800})
_SCF('moat_crashTime', {font = df,size = 20,weight = 800})
_SCF('moat_JackBig', {font = df,size = 50,weight = 800})
_SCF('moat_JackMed', {font = df,size = 40,weight = 800})
_SCF('moat_JackVerySmall', {font = df,size = 15,weight = 800})
_SCF('moat_VersusTitle', {font = df,size = 28,weight = 800})
_SCF('moat_VersusWinner', {font = df,size = 22,weight = 800})
_SCF('moat_ChatFont2', {font = df,size = 20,weight = 1200})
_SCF('moat_ChatFont2', {font = df,size = 20,weight = 1200})
_SCF('moat_Trebuchet24', {font = df,size = 24,weight = 800})
_SCF('moat_raffleHUDFont', {font = df,size = 26,weight = 800})
_SCF('moat_wdl', {font = df,size = 22,weight = 700})
_SCF('moat_wdls', {font = df,size = 22,weight = 700,blursize = 3})
_SCF('moat_wdl2', {font = df,size = 20,weight = 600})
_SCF('moat_wdl2s', {font = df,size = 20,weight = 600,blursize = 3})
_SCF('moat_ItemDescShadow3', {font = df,size = 14,weight = 800,blursize = 2})
_SCF('moat_wdlb3', {font = df,size = 41,weight = 200})
_SCF('moat_wdlb3s', {font = df,size = 41,weight = 500,blursize = 5})
_SCF('WackyTitle', {size = 28,weight = 600})
_SCF('profile.name', {font = df,weight = 500,size = 40,italic = true,shadow = true})
_SCF('profile.steamid', {font = df,weight = 500,size = 20,shadow = true})
_SCF('Snapper Title', {font = 'Roboto Regular',size = 22.1})
_SCF('Roboto 24', {font = 'Roboto Regular',size = 24})
_SCF('Roboto Big', {font = 'Roboto Regular',size = 77.35})
_SCF('Info Text', {font = 'Roboto Medium',size = 17.68})
_SCF('Info Header', {font = 'Roboto Bold',size = 22.1})
_SCF('Info Title', {font = 'Roboto Medium',size = 44.2})
_SCF('Info Tiny', {font = 'Roboto Medium',size = 13.8125})
_SCF('moat_MOTDHead2', {font = df,size = 50,weight = 700})
_SCF('DefaultBold', {font = df,size = 13,weight = 1000})
_SCF('TabLarge', {font = df,size = 13,weight = 700,antialias = false,shadow = true})
_SCF('Trebuchet22', {font = 'Trebuchet MS',size = 22,weight = 900})
_SCF('TargetIDSmall2', {font = df,size = 16,weight = 1000})
_SCF('cool_small', {font = 'coolvetica',size = 20,weight = 400})
_SCF('cool_large', {font = 'coolvetica',size = 24,weight = 400})
_SCF('treb_small', {font = df,size = 14,weight = 700})
_SCF('TraitorState', {font = df,size = 28,weight = 1000})
_SCF('TimeLeft', {font = df,size = 24,weight = 800})
_SCF('HealthAmmo', {font = df,size = 24,weight = 750})
_SCF('TimeLeftSmall', {font = df,size = 20,weight = 800})
_SCF('WinHuge', {font = df,size = 72,weight = 1000,shadow = true})
_SCF('C4ModelTimer', {font = df,size = 30,weight = 0,antialias = false})
_SCF('C4ModelTimer', {font = df,size = 13,weight = 0,antialias = false})
_SCF('C4Timer', {font = df,size = 30,weight = 750})
_SCF('C4ModelTimer', {font = df,size = 13,weight = 0,antialias = false})
_SCF('C4Timer', {font = df,size = 30,weight = 750})
_SCF("ttc_tutorial_id", {font = 'Arial',size = 40})
_SCF("ttc_tutorial_lbl", {font = 'Arial',size = 15,weight = 1000})