player_manager.AddValidModel( "Deathclaw Alpha", "models/deathclaw_player/deathclaw_player_alpha.mdl" )
player_manager.AddValidHands( "Deathclaw Alpha", "models/weapons/arms/deathclaw_alpha_arms.mdl", 0, "00000000" )
player_manager.AddValidModel( "Deathclaw", "models/deathclaw_player/deathclaw_player.mdl" )
player_manager.AddValidHands( "Deathclaw", "models/weapons/arms/deathclaw_arms.mdl", 0, "00000000" )
player_manager.AddValidModel( "Deathclaw Savage", "models/deathclaw_player/deathclaw_player_savage.mdl" )
player_manager.AddValidHands( "Deathclaw Savage", "models/weapons/arms/deathclaw_savage_arms.mdl", 0, "00000000" )
player_manager.AddValidModel( "Deathclaw Albino", "models/deathclaw_player/deathclaw_player_albino.mdl" )
player_manager.AddValidHands( "Deathclaw Albino", "models/weapons/arms/deathclaw_albino_arms.mdl", 0, "00000000" )
player_manager.AddValidModel( "Deathclaw Glowing", "models/deathclaw_player/deathclaw_player_glowing.mdl" )
player_manager.AddValidHands( "Deathclaw Glowing", "models/weapons/arms/deathclaw_glowing_arms.mdl", 0, "00000000" )
player_manager.AddValidModel( "Deathclaw Matriarch", "models/deathclaw_player/deathclaw_player_matriarch.mdl" )
player_manager.AddValidHands( "Deathclaw Matriarch", "models/weapons/arms/deathclaw_matriarch_arms.mdl", 0, "00000000" )